apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jwts.tokens.osg-htc.org
  finalizers: []
spec:
  group: tokens.osg-htc.org
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ['issuer', 'data', 'expiryTime', 'keyId', 'algorithm', 'key']
              properties:
                issuer:
                  type: string
                data:
                  type: object
                  additionalProperties: true
                keyId:
                  type: string
                algorithm:
                  type: string
                  enum: [RS256, ES256]
                key:
                  type: object
                  properties:
                    secret:
                      type: object
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                        key:
                          type: string

                    configMap:
                      type: object
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                        key:
                          type: string

                    value:
                      type: string

                  oneOf:
                    - required: ['secret']
                    - required: ['configMap']
                    - required: ['value']
                expiryTime:
                  type: object
                  properties:
                    days:
                      type: integer
                    hours:
                      type: integer
                    minutes:
                      type: integer
                  oneOf:
                    - required: ['days']
                    - required: ['hours']
                    - required: ['minutes']
                resignBefore:
                  type: object
                  properties:
                    days:
                      type: integer
                    hours:
                      type: integer
                    minutes:
                      type: integer
                  oneOf:
                    - required: ['days']
                    - required: ['hours']
                    - required: ['minutes']
  names:
    kind: JWT
    singular: jwt
    plural: jwts