apiVersion: tokens.osg-htc.org/v1
kind: JWT
metadata:
  name: my-jwt
spec:
  issuer: https://issuer.example.com/
  keyId: my-jwt-key
  data:
    username: john.doe
    role: admin
    scope: "storage.read:/ storage.create:/"
    sub: john.doe
    aud:
      - "https://wlcg.cern.ch/jwt/v1/any"
    wlcg.ver: "1.0"
  expiryTime:
    days: 1
  resignBefore:
    hours: 5
  algorithm: ES256
  key:
    value: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIIphQalRpd3lclrnNmbR8df1/iljebEgI/CLxsmfd4GYoAoGCCqGSM49
      AwEHoUQDQgAEdN/1YF8Q1BGJdmL9zWDMi5D+2Nfc6iAAXXFvA88HPElN+eOxHy0m
      D1ygqiC82+ZMBTqt9l5dn6JFpd2AawPi7A==
      -----END EC PRIVATE KEY-----