apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configMap"]
    verbs: ["get"]
  - apiGroups: ["tokens.osg-htc.org"]
    resources: ["jwts"]
    verbs: ["watch", "get", "list", "patch"]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]